//===
//Code de chargement des fonctions et constantes depuis msvcrt-ruby
//---
//Ecrit par Nuri Yuri (18/04/2014)
//Ajouts de méthodes par Nuri Yuri (19/04/2014)
//===
#include "stdafx.h"

//---
//Initialisation des variable utilisé par l'interface
//---
HMODULE RubyDLL=NULL;
ri_rbi(ruby_init);
ri_rbi(ruby_script);
ri_rbi(ruby_init_loadpath);
ri_rbi(rb_eval_string);
ri_rbi(ruby_finalize);
ri_rbi(rb_define_class);
ri_rbi(rb_check_type);
ri_rbi(rb_define_module);
ri_rbi(rb_define_class_under);
ri_rbi(rb_define_module_under);
ri_rbi(rb_include_module);
ri_rbi(rb_extend_object);
ri_rbi(rb_define_variable);
ri_rbi(rb_define_virtual_variable);
ri_rbi(rb_define_hooked_variable);
ri_rbi(rb_define_readonly_variable);
ri_rbi(rb_define_const);
ri_rbi(rb_define_global_const);
ri_rbi(rb_define_method);
ri_rbi(rb_define_module_function);
ri_rbi(rb_define_singleton_method);
ri_rbi(rb_define_global_function);
ri_rbi(rb_undef_method);
ri_rbi(rb_define_alias);
ri_rbi(rb_define_attr);
ri_rbi(rb_intern);
ri_rbi(rb_intern2);
ri_rbi(rb_id2name);
ri_rbi(rb_class2name);
ri_rbi(rb_obj_classname);
ri_rbi(rb_funcall);
ri_rbi(rb_funcall2);
ri_rbi(rb_funcall_passing_block);
ri_rbi(rb_scan_args);
ri_rbi(rb_gv_set);
ri_rbi(rb_gv_get);
ri_rbi(rb_iv_get);
ri_rbi(rb_iv_set);
ri_rbi(rb_equal);
ri_rbi(rb_raise);
ri_rbi(rb_warning);
ri_rbi(rb_warn);
ri_rbi(rb_fatal);
ri_rbi(rb_each);
ri_rbi(rb_yield);
ri_rbi(rb_yield_values);
ri_rbi(rb_yield_values2);
ri_rbi(rb_block_given_p);
ri_rbi(rb_need_block);
ri_rbi(rb_iterate);
ri_rbi(rb_block_call);
ri_rbi(rb_rescue);
ri_rbi(rb_ensure);
ri_rbi(rb_catch);
ri_rbi(rb_throw);
ri_rbi(rb_data_object_alloc);
ri_rbi(ruby_run);
ri_rbi(ruby_init_stack);
ri_rbi(ruby_sysinit);
ri_rbi(ruby_options);
ri_rbi(ruby_run_node);
ri_rbi(rb_class_boot);
ri_rbi(rb_marshal_dump);
ri_rbi(rb_marshal_load);
ri_rbi(rb_marshal_define_compat);
ri_rbi(rb_class_new_instance);
ri_rbi(rb_define_alloc_func);
ri_rbi(rb_undef_alloc_func);
ri_rbi(rb_get_alloc_func);
ri_rbi(rb_f_require);
ri_rbi(rb_class_get_superclass);
ri_rbi(rb_float_new_in_heap);

ri_rbci(rb_cObject);
ri_rbci(rb_mKernel);
ri_rbci(rb_cFixnum);
ri_rbci(rb_cFloat);
ri_rbci(rb_cTrueClass);
ri_rbci(rb_cSymbol);
ri_rbci(rb_cNilClass);
ri_rbci(rb_cFalseClass);

//Initialisation des pointeurs de fonction et constante.
void initialize_all_functions()
{
	RubyDLL=LoadLibrary(TEXT("msvcrt-ruby200.dll"));
	if(!RubyDLL)
	{
		MessageBox(0,Text_DLL_load_Fail,Text_RI_error,MB_ICONERROR);
		ExitProcess(ReturnCode_DLL_Fail);
	}
	load_rbf(ruby_init);
	load_rbf(ruby_script);
	load_rbf(ruby_init_loadpath);
	load_rbf(rb_eval_string);
	load_rbf(ruby_finalize);
	load_rbf(rb_define_class);
	load_rbf(rb_check_type);
	load_rbf(rb_define_module);
	load_rbf(rb_define_class_under);
	load_rbf(rb_define_module_under);
	load_rbf(rb_include_module);
	load_rbf(rb_extend_object);
	load_rbf(rb_define_variable);
	load_rbf(rb_define_virtual_variable);
	load_rbf(rb_define_hooked_variable);
	load_rbf(rb_define_readonly_variable);
	load_rbf(rb_define_const);
	load_rbf(rb_define_global_const);
	load_rbf(rb_define_method);
	load_rbf(rb_define_module_function);
	load_rbf(rb_define_singleton_method);
	load_rbf(rb_define_global_function);
	load_rbf(rb_undef_method);
	load_rbf(rb_define_alias);
	load_rbf(rb_define_attr);
	load_rbf(rb_intern);
	load_rbf(rb_intern2);
	load_rbf(rb_id2name);
	load_rbf(rb_class2name);
	load_rbf(rb_obj_classname);
	load_rbf(rb_funcall);
	load_rbf(rb_funcall2);
	load_rbf(rb_funcall_passing_block);
	load_rbf(rb_scan_args);
	load_rbf(rb_gv_set);
	load_rbf(rb_gv_get);
	load_rbf(rb_iv_get);
	load_rbf(rb_iv_set);
	load_rbf(rb_equal);
	load_rbf(rb_raise);
	load_rbf(rb_warning);
	load_rbf(rb_warn);
	load_rbf(rb_fatal);
	load_rbf(rb_each);
	load_rbf(rb_yield);
	load_rbf(rb_yield_values);
	load_rbf(rb_yield_values2);
	load_rbf(rb_block_given_p);
	load_rbf(rb_need_block);
	load_rbf(rb_iterate);
	load_rbf(rb_block_call);
	load_rbf(rb_rescue);
	load_rbf(rb_ensure);
	load_rbf(rb_catch);
	load_rbf(rb_throw);
	load_rbf(rb_data_object_alloc);
	load_rbf(ruby_run);
	load_rbf(ruby_init_stack);
	load_rbf(ruby_sysinit);
	load_rbf(ruby_options);
	load_rbf(ruby_run_node);
	load_rbf(rb_class_boot);
	load_rbf(rb_marshal_dump);
	load_rbf(rb_marshal_load);
	load_rbf(rb_marshal_define_compat);
	load_rbf(rb_class_new_instance);
	load_rbf(rb_define_alloc_func);
	load_rbf(rb_undef_alloc_func);
	load_rbf(rb_get_alloc_func);
	load_rbf(rb_f_require);
	load_rbf(rb_class_get_superclass);
	load_rbf(rb_float_new_in_heap);

	load_rbc(rb_cObject);
	load_rbc(rb_mKernel);
	load_rbc(rb_cFixnum);
	load_rbc(rb_cFloat);
	load_rbc(rb_cTrueClass);
	load_rbc(rb_cSymbol);
	load_rbc(rb_cNilClass);
	load_rbc(rb_cFalseClass);
}